app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('signup',views.user_signup,name='signup'),
    path('login',views.user_login,name='login'),
    path('dashboard',views.user_dashboard,name='dashboard'),
    path('logout',views.user_logout,name='logout'),
    path('changepwd',views.user_change_pwd,name='changepwd'),
    path('changepwd2',views.user_change_pwd2,name='changepwd2'),
    path('post',views.user_post,name='post'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('app1/',include('app1.urls',namespace='app1')),
]

app1/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.


class blog(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField(max_length=7000)


class post(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField(max_length=7000)
    posted_date = models.DateField(default=timezone.now)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_posts')

app1/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from django import forms
from app1.models import post



class SignUpForm(UserCreationForm):
    password2 = forms.CharField(label='Re-Enter_Passward',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']  
        labels = {'email':'Email'}


# class UpdateUserProfileForm(UserChangeForm):
#     password = None
#     class Meta:
#         model = User
#         fields = ['username','first_name','last_name','email','date_joined','last_login','is_active']
#         label = {'email':'Email'}


# class UpdateAdminProfileForm(UserChangeForm):
#     password = None
#     class Meta:
#         model = User
#         fields = '__all__'
#         label = {'email':'Email'}

class postform(forms.ModelForm):
    class Meta:
        model = post
        fields = ['id','title','description','posted_date','user_id']

app1/views.py
from django.shortcuts import render
from app1.forms import SignUpForm,postform
from app1.models import post
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm,SetPasswordForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate,update_session_auth_hash,login,logout
from django.core.paginator import Paginator

# Create your views here.


def home(request):
    posts = post.objects.all()
    paginator = Paginator(posts,2)
    pageno = request.GET.get('page')
    pageobj = paginator.get_page(pageno)
    context = {'pageobj':pageobj,'count':paginator.count}
    return render(request,'app1/home.html',context)


def user_signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Registration Succesfull')
    else:
        form = SignUpForm()
    return render(request,'app1/signup.html',{'form':form,'msg':'This is Signup Form'})


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request,data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username,password=password)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Your Account has been Logged Successfully')
                    return HttpResponseRedirect('/app1/dashboard')
        else:
            form = AuthenticationForm()
        return render(request,'app1/login.html',{'form':form,'msg':'Login Page'})
    else:
        return HttpResponseRedirect('/app1/dashboard')


def user_dashboard(request):
    if request.user.is_authenticated:
        return render(request,'app1/dashboard.html',{'msg':'This is Profile Page'})
    else:
        return HttpResponseRedirect('/app1/login')



def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/app1/login')

def user_post(request):
    if request.user.is_authenticated:
        form = postform()
        if request.method == 'POST':
            form =postform(request.POST)
            if form.is_valid():
                form.save()
                form =postform()
                messages.success(request,'Course Added ')    
        return render(request,'app1/post.html',{'form':form,'name':request.user.username})
    else:
        return HttpResponseRedirect('/app1/login') 



def user_change_pwd(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(user=request.user,data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request,form.user)
                messages.success(request,'Password changed successfully')
                return HttpResponseRedirect('/app1/profile')
        else:
            form = PasswordChangeForm(user=request.user)
        return render(request,'app1/changepwd.html',{'form':form})
    else:
        return HttpResponseRedirect('/app1/login')

def user_change_pwd2(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = SetPasswordForm(user=request.user,data=request.POST)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request,form.user)
                messages.success(request,'Password changed successfully')
                return HttpResponseRedirect('/app1/profile')
        else:
            form = SetPasswordForm(user=request.user)
        return render(request,'app1/changepwd2.html',{'form':form})
    else:
        return HttpResponseRedirect('/app1/login')

app1/templates/app1/about.html
{% extends 'base.html' %}
{% block b1 %}
    <h2 class="text-center">{{msg}}</h2>
{% endblock b1 %}

app1/templates/app1/base.html
{% extends 'base.html' %}
{% block b1 %}
    <h2 class="text-center">{{msg}}</h2>
{% endblock b1 %}

app1/templates/app1/changepwd.html
{% extends 'base.html' %}
{% block b1 %}
 <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">SSV</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app1:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<h2 style="text-align:center">{{msg}}</h2> <br><br>
<div  class=" form-group row">
    <div class="col-sm-12 text-center">
    <form action="" method="post">
        {% csrf_token %}
        {% for i in form %}
        <label for="" class="col-sm-1 offset-0">{{i.label_tag}}</label>
            {{i}}{{i.errors|striptags}} <br><br>
        {% endfor %}       
        <input class="btn btn-success col-sm-2" type="submit" value="Login">
    </form>
{% endblock b1 %}
 

app1/templates/app1/changepwd2.html
{% extends 'base.html' %}
{% block b1 %}
 <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">SSV</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app1:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<h2 style="text-align:center">{{msg}}</h2> <br><br>
<div  class=" form-group row">
    <div class="col-sm-12 text-center">
    <form action="" method="post">
        {% csrf_token %}
        {% for i in form %}
        <label for="" class="col-sm-1 offset-0">{{i.label_tag}}</label>
            {{i}}{{i.errors|striptags}} <br><br>
        {% endfor %}       
        <input class="btn btn-success col-sm-2" type="submit" value="Login">
    </form>
{% endblock b1 %}
 

app1/templates/app1/contact.html
{% extends 'base.html' %}
{% block b1 %}
    <h2 class="text-center">{{msg}}</h2>
{% endblock b1 %}

app1/templates/app1/dashboard.html
{% extends 'base.html' %}
{% block b1 %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">SSV</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:changepwd' %}">Change Pwd</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:changepwd2' %}">Reset Pwd</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<br><br><div>
    <a class="btn btn-warning text-center" href="{% url 'app1:post' %}">POST</a>
</div>
    <h2 class="text-center">{{msg}}</h2>
{% endblock b1 %}

app1/templates/app1/home.html
{% extends 'base.html' %}
{% block b1 %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">SSV</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:dashboard' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <h2 class="text-center">{{msg}}</h2>
    {% for i in content %}
        <div class="alert alert-primary">
            <h1>{{i.title}}</h1>
            <h4>by {{i.user_id}}</h4>
        </div>
        <h3 class="alert alert-secondary">{{i.description}}</h3>
    {% endfor %}
    {% for i in pageobj.object_list %}
            <div class="container-fluid">
                <div class="row">
                    <h5 class="alert alert-dark col-sm-8">{{i.title}} - by {{i.user_id}}</h5> 
                    <h5 class="alert alert-dark col-sm-2">username</h5>
                    <h5 class="alert alert-dark col-sm-2">date</h5>
                </div>
            </div>
            <b>{{i.description}}</b>
    {% endfor %}
    <div class="text-center">
        {% if pageobj.has_previous %}
            <a class="btn btn-dark" href="{% url 'home' %}?page={{pageobj.previous_page_number}}">Previous</a>
        {% endif  %}

        {% if pageobj.has_next %}
        <a class="btn btn-dark" href="{% url 'home' %}?page={{pageobj.next_page_number}}">Next</a>
        {% endif  %}
    </div>
{% endblock b1 %}

app1/templates/app1/login.html
{% extends 'base.html' %}
{% block b1 %}
 <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">SSV</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:changepwd' %}">Change Pwd</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<h2 style="text-align:center">{{msg}}</h2> <br><br>
<div  class=" form-group row">
    <div class="col-sm-12 text-center">
    <form action="" method="post">
        {% csrf_token %}
        {% for i in form %}
        <label for="" class="col-sm-1 offset-0">{{i.label_tag}}</label>
            {{i}}{{i.errors|striptags}} <br><br>
        {% endfor %}       
        <input class="btn btn-success col-sm-2" type="submit" value="Login">
    </form>
{% endblock b1 %}
 

app1/templates/app1/navbar.html
{% extends 'base.html' %}
{% block b1 %}
    <h2 class="text-center">{{msg}}</h2>
{% endblock b1 %}

app1/templates/app1/post.html
{% extends 'base.html' %}
{% block b1 %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-5">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">SSV</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:signup' %}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <h2 class="text-center">{{msg}}</h2>
    <div  class=" form-group row">
        <div class="col-sm-12 text-center">
        <form action="" method="post">
            {% csrf_token %}
            {% for i in form %}
            <label for="" class="col-sm-1 offset-0">{{i.label_tag}}</label>
                {{i}}{{i.errors|striptags}} <br><br>
            {% endfor %}       
            <input class="btn btn-success col-sm-2" type="submit" value="upload">
        </form>
{% endblock b1 %}

app1/templates/app1/signup.html
{% extends 'base.html' %}
{% block b1 %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">SSV</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <h2 style="text-align:center">{{msg}}</h2>
    <br><br><form action="" method="post">
        <div  class="form-group row">
            {% csrf_token %}
            {% for i in form %}
                <label for="" class="col-sm-2 offset-sm-4 col-form-label">{{i.label_tag}}</label>             
                <div class="col-sm-3">{{i}}{{i.errors|striptags}}</div>
            {% endfor %} <br><br><br>
        </div>
            <input  class="btn btn-primary col-sm-1 offset-5" type="submit" value="SignUp">
            <a href="{% url 'app1:login' %}"  class="btn btn-success text-white col-sm-1 offset-0">Login</a>
        </div>
    <div class="text-center text-dark">
        {% if messages %}
            {% for m in messages %}
                <h3 {% if m.tags %}
                        class="{{m.tags}}"
                    {% endif %}
                    >{{m}}
                </h3>
        </div>
    </div>
    </form>
        {% endfor %}
    {% endif %}
{% endblock b1 %}

app1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>BLOG</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    </head>
    <body>
        {% comment %} <div class="container">
            <div class="sticy-top">
                <h1 class="text-center p-3 mb-2 bg-info text-dark">Django Web Development : BLOG</h1>
                <a class="btn btn-dark" href="{% url 'home' %}">HOME</a>
                <a class="btn btn-primary" href="{% url 'app1:signup' %}">SIGN UP</a>
                <a class="btn btn-success" href="{% url 'app1:login' %}">LOGIN</a>
            </div> {% endcomment %}
            <div class="c1">
                {% block b1 %}
                {% endblock b1 %}
            </div>
        </div>
    </body>
</html>